# Generated by Django 4.2.10 on 2024-04-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
        ("campaigns", "0002_rename_tiktokbusinessadvertiser_tiktokadvertiser"),
    ]

    operations = [
        migrations.CreateModel(
            name="TiktokAd",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("first_shown", models.DateField()),
                ("last_shown", models.DateField()),
                ("paid_for", models.CharField(max_length=128)),
                ("total_viewers", models.PositiveIntegerField()),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ads",
                        to="campaigns.tiktokadvertiser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegionViewers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_viewers", models.PositiveIntegerField()),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewers",
                        to="ads.tiktokad",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="regions.region"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegionGender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_male", models.BooleanField()),
                ("is_female", models.BooleanField()),
                ("is_unknown", models.BooleanField()),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genders",
                        to="ads.tiktokad",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="regions.region"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegionAge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_age", models.PositiveSmallIntegerField()),
                ("max_age", models.PositiveSmallIntegerField()),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ages",
                        to="ads.tiktokad",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="regions.region"
                    ),
                ),
            ],
        ),
    ]
