# Generated by Django 4.2.10 on 2024-04-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
        ("keywords", "0001_initial"),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleSearchKeywordMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("competition", models.FloatField()),
                ("average_cpc", models.FloatField(verbose_name="avg cpc")),
                (
                    "partners_average_cpc",
                    models.FloatField(verbose_name="part. avg cpc"),
                ),
                ("low_page_bid", models.FloatField()),
                (
                    "partners_low_page_bid",
                    models.FloatField(verbose_name="part. low page bid"),
                ),
                ("high_page_bid", models.FloatField()),
                (
                    "partners_high_page_bid",
                    models.FloatField(verbose_name="part. high page bid"),
                ),
                ("volume_trends_image", models.ImageField(upload_to="volume_trends/")),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="keywords.basekeyword",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="search_metrics",
                        to="regions.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition Metrics",
                "verbose_name_plural": "Competition",
            },
        ),
        migrations.CreateModel(
            name="GoogleAdsHistoricalKeywordMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "average_month_search",
                    models.FloatField(verbose_name="avg month search"),
                ),
                (
                    "partners_average_month_search",
                    models.FloatField(verbose_name="part. avg month search"),
                ),
                ("average_cpc", models.FloatField(verbose_name="avg cpc")),
                (
                    "partners_average_cpc",
                    models.FloatField(verbose_name="part. avg cpc"),
                ),
                ("low_page_bid", models.FloatField()),
                (
                    "partners_low_page_bid",
                    models.FloatField(verbose_name="part. low page bid"),
                ),
                ("high_page_bid", models.FloatField()),
                (
                    "partners_high_page_bid",
                    models.FloatField(verbose_name="part. high page bid"),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historical_metrics",
                        to="keywords.basekeyword",
                    ),
                ),
                (
                    "regions",
                    models.ManyToManyField(
                        related_name="historical_metrics", to="regions.region"
                    ),
                ),
            ],
            options={
                "verbose_name": "Historical Metrics",
                "verbose_name_plural": "Historical",
            },
        ),
        migrations.CreateModel(
            name="GoogleAdsForecastKeywordMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start")),
                ("end_date", models.DateField(verbose_name="end")),
                ("impressions", models.FloatField(verbose_name="impres.")),
                (
                    "partners_impressions",
                    models.FloatField(verbose_name="part. impres."),
                ),
                ("ctr", models.FloatField()),
                ("partners_ctr", models.FloatField(verbose_name="part. ctr")),
                ("average_cpc", models.FloatField(verbose_name="avg cpc")),
                (
                    "partners_average_cpc",
                    models.FloatField(verbose_name="part. avg cpc"),
                ),
                ("clicks", models.FloatField()),
                ("partners_clicks", models.FloatField(verbose_name="part. clicks")),
                ("cost", models.FloatField()),
                ("partners_cost", models.FloatField(verbose_name="part. cost")),
                ("conversions", models.FloatField(verbose_name="convers.")),
                (
                    "partners_conversions",
                    models.FloatField(verbose_name="part. convers."),
                ),
                ("conversion_rate", models.FloatField(verbose_name="convers. rate")),
                (
                    "partners_conversion_rate",
                    models.FloatField(verbose_name="part. convers. rate"),
                ),
                ("average_cpa", models.FloatField(verbose_name="avg cpa")),
                (
                    "partners_average_cpa",
                    models.FloatField(verbose_name="part. avg cpa"),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forecast_metrics",
                        to="keywords.basekeyword",
                    ),
                ),
                (
                    "regions",
                    models.ManyToManyField(
                        related_name="forecast_metrics", to="regions.region"
                    ),
                ),
            ],
            options={
                "verbose_name": "Forecast Metrics",
                "verbose_name_plural": "Forecast",
            },
        ),
        migrations.CreateModel(
            name="CrossroadsKeywordMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lander_keyword", models.CharField(max_length=128)),
                ("clicks", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="keyword_metrics",
                        to="campaigns.crossroadscampaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crossroads Metrics",
                "verbose_name_plural": "Crossroads",
            },
        ),
        migrations.AddConstraint(
            model_name="googlesearchkeywordmetrics",
            constraint=models.UniqueConstraint(
                fields=("keyword", "date", "region"),
                name="unique_google_search_keyword_metrics_for_date_and_region",
            ),
        ),
        migrations.AddConstraint(
            model_name="googleadshistoricalkeywordmetrics",
            constraint=models.UniqueConstraint(
                fields=("keyword", "date"),
                name="unique_google_ads_historical_keyword_metrics_for_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="googleadsforecastkeywordmetrics",
            constraint=models.UniqueConstraint(
                fields=("keyword", "start_date", "end_date"),
                name="unique_google_ads_forecast_keyword_metrics_for_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="crossroadskeywordmetrics",
            constraint=models.UniqueConstraint(
                fields=("campaign", "lander_keyword", "date"),
                name="unique_crossroads_keywords_metrics_for_date",
            ),
        ),
    ]
