# Generated by Django 4.2.10 on 2024-03-19 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0011_auto_20240319_1255"),
    ]

    operations = [
        migrations.CreateModel(
            name="TiktokBusinessCampaignMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("video_play_actions", models.IntegerField()),
                ("video_watched_2s", models.IntegerField()),
                ("video_watched_6s", models.IntegerField()),
                ("video_views_p25", models.IntegerField()),
                ("video_views_p50", models.IntegerField()),
                ("video_views_p75", models.IntegerField()),
                ("video_views_p100", models.IntegerField()),
                ("cost_per_conversion", models.FloatField()),
                ("cpc", models.FloatField()),
                ("ctr", models.FloatField()),
                ("clicks", models.IntegerField()),
                ("spend", models.FloatField()),
                ("conversion", models.FloatField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaigns.tiktokbusinesscampaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrossroadsCampaignMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("revenue", models.FloatField()),
                ("rpc", models.FloatField()),
                ("rpv", models.FloatField()),
                ("total_visitors", models.IntegerField()),
                ("filtered_visitors", models.IntegerField()),
                ("lander_visitors", models.IntegerField()),
                ("lander_searches", models.IntegerField()),
                ("revenue_events", models.IntegerField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaigns.crossroadscampaign",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="tiktokbusinesscampaignmetrics",
            constraint=models.UniqueConstraint(
                fields=("campaign", "date"),
                name="tiktok_business_unique_metrics_for_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="crossroadscampaignmetrics",
            constraint=models.UniqueConstraint(
                fields=("campaign", "date"), name="crossroads_unique_metrics_for_date"
            ),
        ),
    ]
