# Generated by Django 4.2.10 on 2024-03-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_auto_20240319_1245"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "crossroads_metrics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metrics.crossroadscampaignmetrics",
                    ),
                ),
                (
                    "tiktok_business_metrics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metrics.tiktokbusinesscampaignmetrics",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="campaignmetrics",
            constraint=models.UniqueConstraint(
                fields=("tiktok_business_metrics", "crossroads_metrics", "date"),
                name="unique_campaign_metrics_for_date",
            ),
        ),
    ]
