# Generated by Django 4.2.10 on 2024-03-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0012_delete_mergedcampaign_delete_tempcrossroadscampaign_and_more",
        ),
        ("metrics", "0004_auto_20240319_1907"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossroadsKeywordMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lander_keyword", models.CharField(max_length=128)),
                ("clicks", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaigns.crossroadscampaign",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="crossroadskeywordmetrics",
            constraint=models.UniqueConstraint(
                fields=("campaign", "lander_keyword", "date"),
                name="unique_crossroads_keywords_metrics_for_date",
            ),
        ),
    ]
