# Generated by Django 4.2.10 on 2024-03-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0005_crossroadskeywordmetrics_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignmetrics",
            options={"verbose_name_plural": "Campaign Metrics"},
        ),
        migrations.AlterModelOptions(
            name="crossroadskeywordmetrics",
            options={"verbose_name_plural": "Crossroads Keyword Metrics"},
        ),
    ]
