# Generated by Django 4.2.10 on 2024-03-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("keywords", "0006_googleadskeyword"),
        ("metrics", "0007_alter_campaignmetrics_crossroads_metrics_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAdsHistoricalKeywordMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("average_month_search", models.FloatField()),
                ("partners_average_month_search", models.FloatField()),
                ("average_cpc", models.FloatField()),
                ("partners_average_cpc", models.FloatField()),
                ("low_page_bid", models.FloatField()),
                ("partners_low_page_bid", models.FloatField()),
                ("high_page_bid", models.FloatField()),
                ("partners_high_page_bid", models.FloatField()),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historical_metrics",
                        to="keywords.googleadskeyword",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Google Ads Historical Keyword Metrics",
            },
        ),
        migrations.AddConstraint(
            model_name="googleadshistoricalkeywordmetrics",
            constraint=models.UniqueConstraint(
                fields=("keyword", "date"),
                name="unique_google_ads_historical_keyword_metrics_for_date",
            ),
        ),
    ]
