# Generated by Django 4.2.10 on 2024-03-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0009_googleadsforecastkeywordmetrics_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyCampaignMetrics",
            fields=[],
            options={
                "verbose_name": "Short Campaign Metrics",
                "verbose_name_plural": "Short Campaign Metrics",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("metrics.campaignmetrics",),
        ),
        migrations.AlterField(
            model_name="googleadsforecastkeywordmetrics",
            name="average_cpa",
            field=models.FloatField(verbose_name="avg cpa"),
        ),
        migrations.AlterField(
            model_name="googleadsforecastkeywordmetrics",
            name="average_cpc",
            field=models.FloatField(verbose_name="avg cpc"),
        ),
        migrations.AlterField(
            model_name="googleadsforecastkeywordmetrics",
            name="conversion_rate",
            field=models.FloatField(verbose_name="convers. rate"),
        ),
        migrations.AlterField(
            model_name="googleadsforecastkeywordmetrics",
            name="conversions",
            field=models.FloatField(verbose_name="convers."),
        ),
        migrations.AlterField(
            model_name="googleadsforecastkeywordmetrics",
            name="end_date",
            field=models.DateField(verbose_name="end"),
        ),
        migrations.AlterField(
            model_name="googleadsforecastkeywordmetrics",
            name="impressions",
            field=models.FloatField(verbose_name="impres."),
        ),
        migrations.AlterField(
            model_name="googleadsforecastkeywordmetrics",
            name="partners_average_cpa",
            field=models.FloatField(verbose_name="part. avg cpa"),
        ),
        migrations.AlterField(
            model_name="googleadsforecastkeywordmetrics",
            name="partners_average_cpc",
            field=models.FloatField(verbose_name="part. avg cpc"),
        ),
        migrations.AlterField(
            model_name="googleadsforecastkeywordmetrics",
            name="partners_clicks",
            field=models.FloatField(verbose_name="part. clicks"),
        ),
        migrations.AlterField(
            model_name="googleadsforecastkeywordmetrics",
            name="partners_conversion_rate",
            field=models.FloatField(verbose_name="part. convers. rate"),
        ),
        migrations.AlterField(
            model_name="googleadsforecastkeywordmetrics",
            name="partners_conversions",
            field=models.FloatField(verbose_name="part. convers."),
        ),
        migrations.AlterField(
            model_name="googleadsforecastkeywordmetrics",
            name="partners_cost",
            field=models.FloatField(verbose_name="part. cost"),
        ),
        migrations.AlterField(
            model_name="googleadsforecastkeywordmetrics",
            name="partners_ctr",
            field=models.FloatField(verbose_name="part. ctr"),
        ),
        migrations.AlterField(
            model_name="googleadsforecastkeywordmetrics",
            name="partners_impressions",
            field=models.FloatField(verbose_name="part. impres."),
        ),
        migrations.AlterField(
            model_name="googleadsforecastkeywordmetrics",
            name="start_date",
            field=models.DateField(verbose_name="start"),
        ),
        migrations.AlterField(
            model_name="googleadshistoricalkeywordmetrics",
            name="average_cpc",
            field=models.FloatField(verbose_name="avg cpc"),
        ),
        migrations.AlterField(
            model_name="googleadshistoricalkeywordmetrics",
            name="average_month_search",
            field=models.FloatField(verbose_name="avg month search"),
        ),
        migrations.AlterField(
            model_name="googleadshistoricalkeywordmetrics",
            name="partners_average_cpc",
            field=models.FloatField(verbose_name="part. avg cpc"),
        ),
        migrations.AlterField(
            model_name="googleadshistoricalkeywordmetrics",
            name="partners_average_month_search",
            field=models.FloatField(verbose_name="part. avg month search"),
        ),
        migrations.AlterField(
            model_name="googleadshistoricalkeywordmetrics",
            name="partners_high_page_bid",
            field=models.FloatField(verbose_name="part. high page bid"),
        ),
        migrations.AlterField(
            model_name="googleadshistoricalkeywordmetrics",
            name="partners_low_page_bid",
            field=models.FloatField(verbose_name="part. low page bid"),
        ),
    ]
