# Generated by Django 4.2.10 on 2024-03-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
        ("metrics", "0010_proxycampaignmetrics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="googleadsforecastkeywordmetrics",
            name="regions",
            field=models.ManyToManyField(
                related_name="forecast_metrics", to="regions.region"
            ),
        ),
        migrations.AddField(
            model_name="googleadshistoricalkeywordmetrics",
            name="regions",
            field=models.ManyToManyField(
                related_name="historical_metrics", to="regions.region"
            ),
        ),
    ]
