# Generated by Django 4.2.10 on 2024-03-31 12:33

from django.db import migrations


def move_regions_to_forecast_metrics(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ForecastMetrics = apps.get_model("metrics", "GoogleAdsForecastKeywordMetrics")
    _move_regions_to_metrics(ForecastMetrics, db_alias)


def move_regions_to_historical_metrics(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    HistoricalMetrics = apps.get_model("metrics", "GoogleAdsHistoricalKeywordMetrics")
    _move_regions_to_metrics(HistoricalMetrics, db_alias)


def _move_regions_to_metrics(metrics_model, db_alias):
    for obj in metrics_model.objects.using(db_alias).all():
        regions = getattr(obj.keyword, "regions", None)
        if regions:
            obj.regions.set(regions.all())
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "metrics",
            "0011_remove_googleadsforecastkeywordmetrics_unique_google_ads_forecast_keyword_metrics_for_date_and_more",
        ),
        ("keywords", "0007_rename_googleadskeyword_keyword"),
    ]

    operations = [
        migrations.RunPython(move_regions_to_forecast_metrics),
        migrations.RunPython(move_regions_to_historical_metrics),
    ]
