# Generated by Django 4.2.10 on 2024-04-01 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
        ("keywords", "0008_remove_keyword_regions"),
        ("metrics", "0012_auto_20240331_1533"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleSearchKeywordMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("competition", models.FloatField()),
                ("average_cpc", models.FloatField(verbose_name="avg cpc")),
                (
                    "partners_average_cpc",
                    models.FloatField(verbose_name="part. avg cpc"),
                ),
                ("low_page_bid", models.FloatField()),
                (
                    "partners_low_page_bid",
                    models.FloatField(verbose_name="part. low page bid"),
                ),
                ("high_page_bid", models.FloatField()),
                (
                    "partners_high_page_bid",
                    models.FloatField(verbose_name="part. high page bid"),
                ),
                ("volume_trends_image", models.ImageField(upload_to="volume_trends/")),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="keywords.keyword",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="search_metrics",
                        to="regions.region",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Google Search Keyword Metrics",
            },
        ),
        migrations.AddConstraint(
            model_name="googlesearchkeywordmetrics",
            constraint=models.UniqueConstraint(
                fields=("keyword", "date", "region"),
                name="unique_google_search_keyword_metrics_for_date_and_region",
            ),
        ),
    ]
