# Generated by Django 4.2.10 on 2024-04-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0013_googlesearchkeywordmetrics_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignmetrics",
            options={
                "verbose_name": "Full Campaign's",
                "verbose_name_plural": "Full Campaigns'",
            },
        ),
        migrations.AlterModelOptions(
            name="crossroadskeywordmetrics",
            options={
                "verbose_name": "Crossroads Keyword's",
                "verbose_name_plural": "Crossroads Keywords'",
            },
        ),
        migrations.AlterModelOptions(
            name="googleadsforecastkeywordmetrics",
            options={
                "verbose_name": "Forecast Keyword's",
                "verbose_name_plural": "Forecast Keywords'",
            },
        ),
        migrations.AlterModelOptions(
            name="googleadshistoricalkeywordmetrics",
            options={
                "verbose_name": "Historical Keyword's",
                "verbose_name_plural": "Historical Keywords'",
            },
        ),
        migrations.AlterModelOptions(
            name="googlesearchkeywordmetrics",
            options={
                "verbose_name": "Competition Keyword's",
                "verbose_name_plural": "Competition Keywords'",
            },
        ),
        migrations.AlterModelOptions(
            name="proxycampaignmetrics",
            options={
                "verbose_name": "Short Campaign's",
                "verbose_name_plural": "Short Campaigns'",
            },
        ),
    ]
