# Generated by Django 4.2.10 on 2024-04-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("canonical_name", models.CharField(max_length=128)),
                ("country_code", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Removal Planned", "Removal Planned"),
                        ],
                        max_length=128,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
