# Generated by Django 4.2.10 on 2024-04-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={"ordering": ["name"]},
        ),
    ]
