# Generated by Django 5.0.3 on 2024-03-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrossroadsCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=256)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("revenue", models.FloatField()),
                ("rpc", models.FloatField()),
                ("rpv", models.FloatField()),
                ("total_visitors", models.IntegerField()),
                ("filtered_visitors", models.IntegerField()),
                ("lander_visitors", models.IntegerField()),
                ("lander_searches", models.IntegerField()),
                ("revenue_events", models.IntegerField()),
            ],
        ),
    ]
