# Generated by Django 5.0.3 on 2024-03-16 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrossroadsCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=256)),
                ("date", models.DateField()),
                ("revenue", models.FloatField()),
                ("rpc", models.FloatField()),
                ("rpv", models.FloatField()),
                ("total_visitors", models.IntegerField()),
                ("filtered_visitors", models.IntegerField()),
                ("lander_visitors", models.IntegerField()),
                ("lander_searches", models.IntegerField()),
                ("revenue_events", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TiktokBusinessCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=256)),
                ("advertiser_id", models.CharField(max_length=128)),
                ("date", models.DateField()),
                ("video_play_actions", models.IntegerField()),
                ("video_watched_2s", models.IntegerField()),
                ("video_watched_6s", models.IntegerField()),
                ("video_views_p25", models.IntegerField()),
                ("video_views_p50", models.IntegerField()),
                ("video_views_p75", models.IntegerField()),
                ("video_views_p100", models.IntegerField()),
                ("cost_per_conversion", models.FloatField()),
                ("cpc", models.FloatField()),
                ("ctr", models.FloatField()),
                ("clicks", models.IntegerField()),
                ("spend", models.FloatField()),
                ("conversion", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="MergedCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crossroads",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.crossroadscampaign",
                    ),
                ),
                (
                    "tiktok_business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.tiktokbusinesscampaign",
                    ),
                ),
            ],
        ),
    ]
