# Generated by Django 4.2.10 on 2024-04-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TiktokBusinessAdvertiser",
            new_name="TiktokAdvertiser",
        ),
    ]
