# Generated by Django 5.0.3 on 2024-03-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="crossroadscampaign",
            constraint=models.UniqueConstraint(
                fields=("identifier", "date"), name="crossroads_unique_id_for_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="tiktokbusinesscampaign",
            constraint=models.UniqueConstraint(
                fields=("identifier", "date"), name="tiktok_business_unique_id_for_date"
            ),
        ),
    ]
