# Generated by Django 5.0.3 on 2024-03-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TiktokBusinessCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=128)),
                ("name", models.IntegerField()),
                ("advertiser_id", models.CharField(max_length=128)),
                ("video_play_actions", models.IntegerField()),
                ("video_watched_2s", models.IntegerField()),
                ("video_watched_6s", models.IntegerField()),
                ("video_views_p25", models.IntegerField()),
                ("video_views_p50", models.IntegerField()),
                ("video_views_p75", models.IntegerField()),
                ("video_views_p100", models.IntegerField()),
                ("cost_per_conversion", models.FloatField()),
                ("cpc", models.FloatField()),
                ("ctr", models.FloatField()),
                ("clicks", models.IntegerField()),
                ("spend", models.FloatField()),
                ("conversion", models.FloatField()),
            ],
        ),
    ]
