# Generated by Django 4.2.10 on 2024-04-16 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
        ("campaigns", "0002_rename_tiktokbusinessadvertiser_tiktokadvertiser"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiktokadvertiser",
            name="name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="tiktokadvertiser",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tiktok_advertisers",
                to="regions.region",
            ),
        ),
        migrations.AddField(
            model_name="tiktokadvertiser",
            name="total_ads",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
