# Generated by Django 5.0.3 on 2024-03-16 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_tiktokbusinesscampaign"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergedCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crossroads",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.crossroadscampaign",
                    ),
                ),
                (
                    "tiktok_business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.tiktokbusinesscampaign",
                    ),
                ),
            ],
        ),
    ]
