# Generated by Django 5.0.3 on 2024-03-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_crossroadscampaign_crossroads_unique_id_for_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossroadsToTiktokBusinessIdentifiers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tiktok_business", models.CharField(max_length=128, unique=True)),
                ("crossroads", models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
