# Generated by Django 5.0.3 on 2024-03-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_mergedcampaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiktokbusinesscampaign",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
