# Generated by Django 4.2.10 on 2024-04-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_tiktokadvertiser_name_tiktokadvertiser_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiktokadvertiser",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="tiktokadvertiser",
            name="facebook",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="tiktokadvertiser",
            name="linkedin",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="tiktokadvertiser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="tiktokadvertiser",
            name="youtube",
            field=models.URLField(max_length=256, null=True),
        ),
    ]
