# Generated by Django 4.2.10 on 2024-04-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_tiktokadvertiser_email_tiktokadvertiser_facebook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiktokadvertiser",
            name="website",
            field=models.URLField(null=True),
        ),
    ]
