# Generated by Django 4.2.10 on 2024-03-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_auto_20240318_1127"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mergedcampaign",
            name="date",
            field=models.DateField(),
        ),
    ]
