# Generated by Django 4.2.10 on 2024-04-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_tiktokadvertiser_website"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tiktokadvertiser",
            options={
                "verbose_name": "Tiktok Advertiser",
                "verbose_name_plural": "Tiktok Advertisers",
            },
        ),
    ]
