# Generated by Django 4.2.10 on 2024-03-18 09:48

from django.db import migrations, models


def delete_duplicates_for_date(apps, schema_editor):
    MergedCampaign = apps.get_model("campaigns", "MergedCampaign")
    db_alias = schema_editor.connection.alias
    groups = (
        MergedCampaign.objects.using(db_alias)
        .values("tiktok_business", "date")
        .annotate(min_id=models.Min("id"))
    )
    first_ids = [obj["min_id"] for obj in groups]
    MergedCampaign.objects.exclude(id__in=first_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_alter_mergedcampaign_date"),
    ]

    operations = [
        migrations.RunPython(delete_duplicates_for_date),
    ]
