# Generated by Django 4.2.10 on 2024-03-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0007_auto_20240318_1148"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mergedcampaign",
            constraint=models.UniqueConstraint(
                fields=("tiktok_business", "crossroads", "date"),
                name="merged_campaign_unique_for_date",
            ),
        ),
    ]
