# Generated by Django 4.2.10 on 2024-03-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_mergedcampaign_merged_campaign_unique_for_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CrossroadsCampaign",
            new_name="TempCrossroadsCampaign",
        ),
        migrations.RenameModel(
            old_name="TiktokBusinessCampaign",
            new_name="TempTiktokBusinessCampaign",
        ),
    ]
