# Generated by Django 4.2.10 on 2024-03-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0009_rename_crossroadscampaign_tempcrossroadscampaign_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossroadsCampaign",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="TiktokBusinessAdvertiser",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TiktokBusinessCampaign",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaigns.tiktokbusinessadvertiser",
                    ),
                ),
            ],
        ),
    ]
