# Generated by Django 4.2.10 on 2024-03-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0011_auto_20240319_1255"),
        ("metrics", "0004_auto_20240319_1907"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mergedcampaign",
            options={
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="tempcrossroadscampaign",
            options={
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="temptiktokbusinesscampaign",
            options={
                "managed": False,
            },
        ),
    ]
