# Generated by Django 4.2.10 on 2024-03-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0011_auto_20240319_1255"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MergedCampaign",
        ),
        migrations.DeleteModel(
            name="TempCrossroadsCampaign",
        ),
        migrations.DeleteModel(
            name="TempTiktokBusinessCampaign",
        ),
    ]
