# Generated by Django 4.2.10 on 2024-03-20 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0012_delete_mergedcampaign_delete_tempcrossroadscampaign_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crossroadstotiktokbusinessidentifiers",
            options={
                "verbose_name_plural": "Crossroads To Tiktok Business Identifiers"
            },
        ),
        migrations.AlterField(
            model_name="tiktokbusinesscampaign",
            name="advertiser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="campaigns.tiktokbusinessadvertiser",
            ),
        ),
    ]
