# Generated by Django 4.2.10 on 2024-03-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0013_alter_crossroadstotiktokbusinessidentifiers_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CrossroadsToTiktokBusinessIdentifiers",
            new_name="TempCrossroadsToTiktokBusinessIdentifiers",
        ),
    ]
