# Generated by Django 4.2.10 on 2024-03-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0014_rename_crossroadstotiktokbusinessidentifiers_tempcrossroadstotiktokbusinessidentifiers",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossroadsToTiktokBusinessIdentifiers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crossroads",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identifiers",
                        to="campaigns.crossroadscampaign",
                    ),
                ),
                (
                    "tiktok_business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identifiers",
                        to="campaigns.tiktokbusinesscampaign",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Crossroads To Tiktok Business Identifiers",
            },
        ),
    ]
