# Generated by Django 4.2.10 on 2024-03-20 11:07

from django.db import migrations


def create_identifiers(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    TempIdentifiers = apps.get_model(
        "campaigns", "TempCrossroadsToTiktokBusinessIdentifiers"
    )
    Identifiers = apps.get_model("campaigns", "CrossroadsToTiktokBusinessIdentifiers")
    TiktokBusinessCampaign = apps.get_model("campaigns", "TiktokBusinessCampaign")
    CrossroadsCampaign = apps.get_model("campaigns", "CrossroadsCampaign")

    objs = []
    for temp_obj in TempIdentifiers.objects.using(db_alias).all():
        tiktok_business = TiktokBusinessCampaign.objects.filter(
            id=temp_obj.tiktok_business
        ).first()
        crossroads = CrossroadsCampaign.objects.filter(id=temp_obj.crossroads).first()

        if tiktok_business and crossroads:
            objs.append(
                Identifiers(
                    tiktok_business=tiktok_business,
                    crossroads=crossroads,
                )
            )

    Identifiers.objects.bulk_create(objs, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0015_crossroadstotiktokbusinessidentifiers"),
    ]

    operations = [
        migrations.RunPython(create_identifiers),
    ]
