# Generated by Django 4.2.10 on 2024-03-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0016_auto_20240320_1307"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tempcrossroadstotiktokbusinessidentifiers",
            options={
                "managed": False,
                "verbose_name_plural": "Crossroads To Tiktok Business Identifiers",
            },
        ),
    ]
