# Generated by Django 4.2.10 on 2024-03-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("keywords", "0002_crossroadskeyword_crossroads_unique_keyword_for_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CrossroadsKeyword",
            new_name="TempCrossroadsKeyword",
        ),
    ]
