# Generated by Django 4.2.10 on 2024-04-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keywords", "0002_basekeyword_marketing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basekeyword",
            name="marketing",
            field=models.CharField(
                blank=True,
                choices=[("", ""), ("B2C", "B2C"), ("B2B", "B2B")],
                default="",
                max_length=64,
            ),
        ),
    ]
