# Generated by Django 4.2.10 on 2024-04-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keywords", "0003_alter_basekeyword_marketing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basekeyword",
            name="text",
            field=models.CharField(max_length=256),
        ),
    ]
