# Generated by Django 4.2.10 on 2024-03-19 19:04

from django.db import migrations


def create_crossroads_keyword_metrics(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    TempMetrics = apps.get_model("keywords", "TempCrossroadsKeyword")

    Metrics = apps.get_model("metrics", "CrossroadsKeywordMetrics")

    instances = []
    for obj in TempMetrics.objects.using(db_alias).all():
        instances.append(
            Metrics(
                campaign_id=obj.campaign_id,
                lander_keyword=obj.lander_keyword,
                clicks=obj.clicks,
                date=obj.date,
            )
        )
    Metrics.objects.using(db_alias).bulk_create(instances, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("keywords", "0003_rename_crossroadskeyword_tempcrossroadskeyword"),
        ("metrics", "0005_crossroadskeywordmetrics_and_more"),
    ]

    operations = [
        migrations.RunPython(create_crossroads_keyword_metrics),
    ]
