# Generated by Django 4.2.10 on 2024-03-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("keywords", "0004_auto_20240319_2104"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tempcrossroadskeyword",
            options={
                "managed": False,
            },
        ),
    ]
