# Generated by Django 4.2.10 on 2024-03-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
        ("keywords", "0005_delete_tempcrossroadskeyword"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAdsKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=256)),
                (
                    "regions",
                    models.ManyToManyField(
                        related_name="keywords", to="regions.region"
                    ),
                ),
            ],
        ),
    ]
