# Generated by Django 4.2.10 on 2024-03-31 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0010_proxycampaignmetrics_and_more"),
        ("regions", "0001_initial"),
        ("keywords", "0006_googleadskeyword"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GoogleAdsKeyword",
            new_name="Keyword",
        ),
    ]
