# Generated by Django 4.2.10 on 2024-03-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "metrics",
            "0012_auto_20240331_1533",
        ),
        ("keywords", "0007_rename_googleadskeyword_keyword"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="regions",
        ),
    ]
