# Generated by Django 4.2.10 on 2024-04-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keywords", "0008_remove_keyword_regions"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="is_generated_by_chat_gpt",
            field=models.BooleanField(default=False),
        ),
    ]
