# Generated by Django 4.2.10 on 2024-04-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keywords", "0009_keyword_is_generated_by_chat_gpt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="text",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
